### ISSUE TITLE
docker缺省配置为什么会提示Username for 'https://xxx.net'，这是bug还是我使用问题。

### ISSUE THREAD

**Issue by maxadc** [WJQSERVER-STUDIO/ghproxy#81]
设置 docker 为5007
```
version: '3.9'
services:
    ghproxy:
        image: 'wjqserver/ghproxy:latest'
        restart: always
        volumes:
            - 'ghproxy/log/run:/data/ghproxy/log'
            - 'ghproxy/log/caddy:/data/caddy/log'
            - ‘ghproxy/config:/data/ghproxy/config'
        ports:
            - '5007:8080'
```
caddy反代 
```
https://xxx.net {
   reverse_proxy http://127.0.0.1:5007
}
```
可以正常打开网页。也就是部署没问题。
git clone https://xxxs.net/https://github.com/yourusername/Crawl4AI.git
Cloning into 'Crawl4AI'...
Username for 'https://xxx.net':
配置文件我没改，默认的，我看了，没设定授权。

authMethod = "parameters" # "header" or "parameters"
authToken = "token"
enabled = false
passThrough = false
ForceAllowApi = false
最后我骂一句，尼玛哪个生孩子没屁眼的，把代理网站全举报了。也不怕断子绝孙，遭天谴吗！艹
